//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Space_Station : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 LeftTouchpadLocation
        {
            get
            {
                return SteamVR_Actions.space_Station_LeftTouchpadLocation;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftTouchpadPressed
        {
            get
            {
                return SteamVR_Actions.space_Station_LeftTouchpadPressed;
            }
        }
        
        public virtual SteamVR_Action_Boolean ActionPressed
        {
            get
            {
                return SteamVR_Actions.space_Station_ActionPressed;
            }
        }
        
        public virtual SteamVR_Action_Boolean Grab
        {
            get
            {
                return SteamVR_Actions.space_Station_Grab;
            }
        }
    }
}
